; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[common]
framework = arduino
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	adafruit/Adafruit GFX Library@^1.12.1
	adafruit/Adafruit BusIO@^1.17.4
	kosme/arduinoFFT@^2.0.4

[env:esp32-s3-dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.psram_type = opi
build_flags =
	-DBOARD_S3_DEV
	-DBOARD_HAS_PSRAM
lib_deps =
	${common.lib_deps}
